### PR TITLE
Manage -> Category -> Symbol 

### PR DESCRIPTION
**Pull request by guanlisheng**
The idea is to provide a basic management function upon `CategoryData.categoryToSFSymbol` and store the mapping (category name -> symbol) in `userDefaults`

- for display, get Symbol from `CategoryData.categoryToSFSymbo || UserDefaults.standard.dictionary`.
- for editing,  use `CategoryData.categoryToSFSymbo` as the picker data source and update category name -> symbol in `UserDefaults.standard.dictionary`
- note: the key is Name instead of ID and update category2symbol map will not impact existing data much

### CODE REVIEW

**Comment by guanlisheng** [comment]
hi @georgeef, any advice on `UserDefaults.standard.dictionary` ?

**Comment by georgeef** [comment]
The key should better be the FullName (the whole path), which is already unique. The Name (the last part only) is not unique, and it creates new limitations and complications. I personally use a category tree with several common leaf names, in which the most important information is in the path before the leaf name (the significance reduces from root to leaves). Maybe many other users do something similar.

**Comment by georgeef** [comment]
I need some time to review. You can merge anyway and we can add/fix what is missing later.

**Comment by georgeef** [comment]
If the symbols are local to the iOS app (not to be synchronized), why don't we use the ID as key?  It will make the symbol maintenance much simple, e.g., if the user renames a category the map is still valid.

**Comment by guanlisheng** [comment]
It is still WIP and the editing piece will be on your existing Preference framework.

- FullName will be a good suggestion, and we can combine both.  something exactly matches the first
- Name over ID is due to both simplification and sync, different databases may have different categories for the given ID.
- Enabling/Disabling would be a good suggestion, should be added into Settings as well.

**Pull request merged**
