### PR TITLE
Issue 21 & Transaction View Design Changes

### PR DESCRIPTION
**Pull request by Jnolcox**
- #21
- #27

### CODE REVIEW

**Comment by guanlisheng** [comment]
Hi @georgeef, thoughts?

Let's dive into two issues: 1. renaming and 2. enum value.

The enum value inconsistency in the enum values might be due to some code for the mmex4desktop.

`mmchecking_list.cpp`
```
    switch (evt)
    {    
    case MENU_TREEPOPUP_MARKRECONCILED:         status = "R"; break;
    case MENU_TREEPOPUP_MARKUNRECONCILED:       status = ""; break;
    case MENU_TREEPOPUP_MARKVOID:               status = "V"; break;
    case MENU_TREEPOPUP_MARK_ADD_FLAG_FOLLOWUP: status = "F"; break;
    case MENU_TREEPOPUP_MARKDUPLICATE:          status = "D"; break;
    default: wxASSERT(false);
    
```

`model/Model_Checking.cpp`
```
    STATUS_ENUM ret = NONE;
    if (r.CmpNoCase("R") == 0) ret = RECONCILED;
    else if (r.CmpNoCase("V") == 0) ret = VOID_;
    else if (r.CmpNoCase("F") == 0) ret = FOLLOWUP;
    else if (r.CmpNoCase("D") == 0) ret = DUPLICATE_;
    cache.insert(std::make_pair(r, ret));
```

**Comment by georgeef** [comment]
About the tab name: `Checking` and `Manage -> Data -> Transactions` have a big overlap but they are not the same. In the future `Checking` will also contain executions of scheduled transactions, maybe also other features. Its purpose is to provide easy access to most often needed information and operations. On the other hand, `Transactions` is focusing on one database table, like other items under `Manage -> Data`.

We reserve the name `Transactions` for the database table `CHECKINGACCOUNT_V1`. Also we reserve the name `Scheduled` (or `Recurring`) for the database table `BILLSDEPOSITS_V1`. To avoid confusion, the name of the first (leftmost) tab must be something different.

**Comment by georgeef** [comment]
About TransactionStatus: MMEX Desktop uses the name `Unreconciled` instead of `none`. Although it is more descriptive, I personally don't like it: linguistically `unreconciled` means not reconciled, but this case is only one of the cases that are not reconciled. On the other hand, the term `unreconciled balance`, when used in reports, usually means all TransactionStatus cases (except `void`), including reconciled. I would avoid using the term `unreconciled` as one of the cases in TransactionStatus, because it doesn't have a clear meaning.

I also don't like the current implementation: none means "none of the status flags", but it appears itself with the flag `N` in the transaction edit interface (in this respect "-" or no flag would be more consistent with its name), and the choice `None` inside the first picker in `Insights` is very little descriptive and quite confusing.

More important than the internal name is the value written in the database file. MMEX Desktop writes '' for what it calls Unreconciled, mmex-ios writes 'N' for what is calls none. At the read side they are both consistent, they translate '', 'N', 'n', or anything else except [RrVvFfDd] to what is called Unreconciled in Desktop or what is called none in mmex-ios.

@guanlisheng What does MMEX4Android write in the database for status none?

If MMEX Desktop and MMEX4Android are consistent, I think it is better for mmex-ios to also be consistent with them.

My preferences: Between `unreconciled` and `none` I prefer the second, it better describes what it does. In the transaction edit interface I prefer '-' than 'N'. For what we write in the database file, we should be fully compatible with MMEX Desktop. Database conventions are hard to change, even if they are bad, because they have been used for long time.

**Comment by guanlisheng** [comment]
I'm ok with this your proposal, @georgeef 

@Jnolcox can you help to refine this PR to focus on the enum value/name only?

**Comment by Jnolcox** [comment]
> I'm ok with this your proposal, @georgeef
> 
> @Jnolcox can you help to refine this PR to focus on the enum value/name only?

@guanlisheng for sure - I'll refactor now.

**Pull request closed without merging**
